name: Build and Test Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2
    - name: Install FFMPEG
      run: sudo apt update && sudo apt install ffmpeg 
    
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run test
      run: vendor/bin/phpunit tests/FFMpegLaravelTest.php
      
    - name: Output file artifact
      uses: actions/upload-artifact@v2
      with:
        name: Output file - egg.mp3
        path: /tests/output/egg.mp3 || /tests/output/muted_egg.mp4 || /tests/output/Newegg.mp4 || /tests/output/newSmall.gif || /tests/output/newSmall.mp4 || /tests/output/resized_egg.mp4 || /tests/output/thumbnail.jpg
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
